### ISSUE TITLE
The # symbol stops translation

### ISSUE THREAD

**Issue by CactiChameleon9** [walking-octopus/translate-ut#1]
![screenshot20220423_105532959](https://user-images.githubusercontent.com/51231053/164889692-a90f1f36-b1c5-45b5-afba-67be3a9f2657.png)
![screenshot20220423_105730745](https://user-images.githubusercontent.com/51231053/164889750-b39d1a55-43ed-455e-bfba-08bd1be8095d.png)

**Comment by walking-octopus** [comment]
Something might be wrong with encoding special characters when making a request. I'll fix this later. Thanks for discovering this bug!

**Comment by walking-octopus** [comment]
Fixed in the last commit!

**Comment by CactiChameleon9** [comment]
Thanks for fixing this so quickly

**Comment by walking-octopus** [comment]
Have a lovely day!
