### ISSUE TITLE
Copy (partial, full) of the translation.

### ISSUE THREAD

**Issue by gbdomubpkm** [walking-octopus/translate-ut#3]
Always good to have a good translator who respects privacy. Thank you.
It seems to me that the priority is to make the translation copyable (partially, fully) and therefore pasteable so that it is fully functional and useful.

 - [x] Partial 
 - [x] Full copy

**Comment by walking-octopus** [comment]
Fixed in the last commit. It will be included in the next release.

**Comment by gbdomubpkm** [comment]
Thank you for the click test.

**Comment by walking-octopus** [comment]
Open the new issue for it. How did I not think of it earlier?

**Comment by walking-octopus** [comment]
Here's a demo!

[translate.walking-octopus_1.0.2_all_1.zip](https://github.com/walking-octopus/translate-ut/files/8550445/translate.walking-octopus_1.0.2_all_1.zip)

**Comment by gbdomubpkm** [comment]
ok. The setting bar starts way too low i think. it's microscopic! 😨 It should start at the current 35 or 40 in my opinion and go up to 60 ?

**Comment by walking-octopus** [comment]
Fixed in the last commit!
[translate.zip](https://github.com/walking-octopus/translate-ut/files/8553109/translate.zip)

**Comment by gbdomubpkm** [comment]
For me, that's ok. Thanks !

**Comment by walking-octopus** [comment]
Full copy was added in the last update.
