### ISSUE TITLE
Clear button

### ISSUE THREAD

**Issue by gbdomubpkm** [walking-octopus/translate-ut#4]
I think a one-step mechanism (button, swipe of a finger..) to completely reset the window containing the text to be translated would be useful.
Currently, the total deletion of a text, whether translated or not, requires several manipulations.

**Comment by walking-octopus** [comment]
The clear button ties into the bottom bar branch. Unfortunately, I might not have the time to work on it, though it's already half done. When I'll have time, I'll look into solving it.

**Comment by walking-octopus** [comment]
Done!

**Comment by gbdomubpkm** [comment]
Thanks very much 
That works very well.
But what is the use of this white rectangle that in my opinion is unsightly and which appears for a few seconds during a reset, or during the global selection of the translation? Does it have a real function? I think, at the very least, that its appearance time should be cut in half. Isn't it ?
![Rect blanc](https://user-images.githubusercontent.com/50362604/170811382-49671f1f-8607-4bf2-869a-2040bbd6548d.png)

**Comment by walking-octopus** [comment]
You've found a bug. This is a toast message. I accidentally mixed up the white and black in its background color. I've fixed this and reduced its appearance time in half. Thank you for reporting it.

**Comment by gbdomubpkm** [comment]
Thanks.
Everything is ok now. However, I think that the popup presence time can finally be reduced again during a next update.
